openapi: 3.1.1
info:
  title: Geoguess Lite
  version: "1.0.0"
paths:
  /health:
    $ref: ./paths/health.yml
  /users/me:
    $ref: ./paths/users-me.yml
  /daily-challenges/today:
    $ref: ./paths/daily-challenges-today.yml
components:
  schemas:
    User:
      $ref: ./components/schemas/user.yml
    DailyChallenge:
      $ref: ./components/schemas/daily-challenge.yml
    ErrorResponse:
      $ref: ./components/schemas/error-response.yml
  requestBodies:
    CreateUserRequest:
      $ref: ./components/requestBodies/user-me-post.yml
    UpdateUserRequest:
      $ref: ./components/requestBodies/user-me-patch.yml
